---
title: ''
author: "Anton Sobolev"
email: anton.sobolev@utdallas.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=.75in
jobtitle: Assistant Professor, School of Economic, Political and Policy Sciences
keywords: R Markdown, academic CV, template
linkcolor: Brown
fontawesome: yes
address:  Cecil H. Green Hall | 800 West Campbell Road, GR 3.108 | Richardson, TX 75080-3021
updated: no
urlcolor: Brown
web: sobolev.app
xcolor: yes
---

# EDUCATION

**University of California, Los Angeles**, Ph.D., Government  \hfill 2019

**University of California, Los Angeles**, M.Sc., Statistics  \hfill 2019

**Higher School of Economics**, M.A., Public Economics (with Honors)  \hfill 2011

**Higher School of Economics,** B.A., Political Science (with Honors)  \hfill 2009

<!--
\hskip 1cm  Topic: "*Dictators in the Spotlight*: What They Do When They Cannot Do Business as Usual"

\hskip 1cm  Committee: Prof. Daniel Treisman (chair), Prof. Barbara Geddes,

\hskip 1cm Prof. Chad Hazlett, Prof. Daniel Posner, Prof. Jeniffer Pan (Stanford)

**Higher School of Economics, Moscow**, Ph.D., Public Economics  \hfill 2015

-->

# ACADEMIC POSITIONS

**Assistant Professor**, School of Economic, Political and Policy Sciences, \hfill 2021- 
 
The University of Texas at Dallas 

**Postdoctoral Associate**, MacMillan Center for International Studies, Yale University \hfill 2019-21 

**Research Fellow**, Luskin School of Public Affairs, UCLA \hfill 2018 

**Teaching Fellow**, **Research Fellow**, Anderson School of Business, UCLA \hfill 2018 

**Teaching Fellow**, **Research Fellow**, Department of Political Science, UCLA \hfill 2014-17

**Research Fellow**, Center for the Study of Institutions and Development, \hfill 2013-14

Higher School of Economics

**Visiting Research Fellow**, Russian & East European Institute, Indiana University  \hfill 2012

**Lecturer**, Political Science Department, Higher School of Economics \hfill 2010-13 

**Research Fellow**, Political Studies Lab, Higher School of Economics \hfill 2008-13

# TEACHING 
**UT Dallas**, ***School of Economic, Political and Policy Sciences***

\hskip 1cm Conflict in Cyberspace (F'22-'F25)

\hskip 1cm Capstone in Cyber: Security and Policy (S'22-S'25)

\hskip 1cm Open-Source Intelligence (S'24-S'25)

\hskip 1cm Cyber Policy (F'21)

**Yale University**, ***Department of Political Science***

\hskip 1cm Big Data, AI, and Russian Politics (S'20, S'21)

**University of California, Los Angeles**, ***Anderson School of Business***

\hskip 1cm Technology Analytics (MBA), with Keith Chen (S/F'18)

\hskip 1cm Competitive Analytics (MSBA), with Keith Chen (S/F'18)

# RESEARCH

## Articles

[**"The Last Call for Authenticity: AI Reshaping Voice Fraud Landscape,"**](https://doi.org/10.1080/23738871.2025.2597191) *Journal of Cyber Policy*, 2025, 1-21

[**"Diminished Quality-of-Life and Psychosocial Strain of Women under the New Taliban Era,"**](https://doi.org/10.3390/soc16010009) *Societies*, 2025, 16(1): 9 (with Jessi Hanson-DeFusco and others) 

[**"Quality of Life and Afghan Adults’ Psychosocial Wellbeing Under Taliban 2.0,"**](https://doi.org/10.1371/journal.pmen.0000118) *PLOS Mental Health*, 2025, 2(1):1  (with Jessi Hanson-DeFusco, Abdul Stanekzai, Alexis McMaster, Hamid Popalzai, Heer Shah, Min Shi, and Nandita Kumar)

[**"News and Geolocated Social Media Accurately Measure Protest Size Variation,"**](https://doi.org/10.1017/S0003055420000295) *American Political Science Review*, 2020, 114(4):1343-1351 (with Keith Chen, Jungseock Joo, and Zachary Steinert-Threlkeld)

[**"Stability of Revolutionary Governments in The Face of Mass Protest,"**](https://doi.org/10.1016/j.ejpoleco.2019.08.003) *European Journal of Political Economy*, 2019, 60:2-20 (with Dmitry Dagaev and Natalia Lamberova)

[**"Trial by Fire: a Natural Disaster’s Impact on Support for the Authorities in Rural Russia,"**](http://dx.doi.org/10.1017/S0043887114000215) *World Politics*, 2014, 66(4): 641-668  (with Egor Lazarev, Irina Soboleva, and Boris Sokolov) 

[**"Means of Production VS Means of Coercion: Can Russian Business Limit the Violence of Predatory State?,"**](http://www.tandfonline.com/doi/full/10.1080/1060586X.2013.859434) *Post-Soviet Affairs*, 2014, 30(1), 171-194 (with Andrei Yakovlev and Anton Kazun)

[**"Social and Economic Policy Trade-Offs in the Russian Regions: Evidence from Four Case Studies,"**](http://www.tandfonline.com/doi/full/10.1080/09668136.2013.838055) *Europe-Asia Studies*, 2013, 65(10): 1855-1876 (with Tom Remington, Irina Soboleva, and Mark Urnov) 

[**"Well-Organized Play: Symbolic Politics and the Effect of the Pro-Putin Rallies,"**](https://doi.org/10.2753/PPC1075-8216600203) *Problems of Post-Communism*, 2013, 60(2):24-39 (with Regina Smyth and Irina Soboleva) 


## Peer-reviewed book chapters

[**"Civic and Political Activism in Russia,"**](http://www.jstor.org/stable/10.7864/j.ctt1zkjzsh.13) in *The New Autocracy: Information, Politics, and Policy in Putin's Russia*, 2018, 249-276, Brookings Institution Press (with Alexei Zakharov)

[**"Defining Common Ground: Collective Identity in Russia's Post-Election Protests and Rallies"**](https://AntonSobolev.github.com/files/2013-Defining-Commong-Ground.pdf) in *The Systemic and Non-Systemic Opposition in the Russian Federation*, 2015, 51-76, Ashgate Publishing (with Regina Smyth and Irina Soboleva)


# GRANTS

The Harriman Institute, Columbia University, Research Grant (18,000$)  \hfill 2019 

Charles Koch Foundation, Arlington, Research Fellowship (5,000$)  \hfill 2019 

Dissertation Year Fellowship, Los Angeles, UCLA (64,000$) \hfill 2018

The Harriman Institute, Columbia University, Travel Grant (4,000$) \hfill 2018 

Institute for Humane Studies, Arlington, Travel Grant (5,000$)  \hfill 2018

Higher School of Economics, Moscow, Alumni Academic Fellowship (3,000$) \hfill 2017

Carnegie Corporation of New York, New York, Book Project Grant (600,000$) \hfill 2014-16

Institute for Humane Studies, Arlington, PhD Fellowship (22,500$)  \hfill 2014-18 

Oxford-Russia Foundation, Research Fellowship (6,000$) \hfill  2007-10 

# AWARDS AND DISTINCTIONS

Higher School of Economics Award for Academic Achievements \hfill 2012 

“The Best Lecturer of Political Science Department - 2012” Award \hfill 2012 

High Distinction for Honors Thesis, Higher School of Economics \hfill  2011 

High Distinction for Honors Thesis, Higher School of Economics \hfill  2009

# SELECTED PRESENTATIONS

APSA (2023, 2021, 2018, 2016, 2014), MPSA (2024, 2022, 2018, 2017, 2014), Annual conference of the Society for Political Methodology (2019), European Economic Association Annual Conference (2015), [New York University (2021)](https://www.youtube.com/watch?v=6_3E39SH688), Yale University (2020), Society for Institutional & Organizational Economics Annual Conference (2013), April International Academic Conference On Economic and Social Development (2013, 2012, 2010, 2011), Moscow Higher School of Economics (2021, 2017, 2013, 2017), Indiana University (2012)



# SERVICE

**Reviewer:** American Political Science Review, American Journal of Political Science, Comparative Political Studies, Computational Communication Research, Economics and Politics, Foreign Policy Analysis, New Media and Society, Journal of International Affairs, Problems of Post-Communism, Post-Soviet Affairs

<!-- 
# REFERENCES

Prof. Daniel Treisman (chair of the Ph.D. dissertation committee), Department of Political Science, UCLA, 4289 Bunche Hall, Los Angeles, CA 90095, [treisman@polisci.ucla.edu](treisman@polisci.ucla.edu)

Prof. Chad Hazlett (chair of the M.Sc. dissertation committee), Department of Statistics, UCLA, 8105G Mathematical Sciences, Los Angeles, CA 90095, [chazlett@ucla.edu](chazlett@ucla.edu)

Prof. Konstantin Sonin (chair of the M.A. dissertation committee), Harris Public Policy School, University of Chicago, 1155 E60 St, Chicago, IL 60637, [ksonin@uchicago.edu](ksonin@uchicago.edu)


**University of California, Los Angeles**, ***Department of Political Science***

\hskip 1cm Politics and Government of Post-Communist Russia, with Prof. Daniel Treisman ('14-'17)

\hskip 1cm Diversity, Disagreement, and Democracy, with Prof. Susanne Lohmann ('16)

\hskip 1cm Data Analysis, with Prof. Erin Hartman ('18)

\hskip 1cm Politics and Strategy, with Prof. Michael Chwe ('17)
-->


